### ISSUE TITLE
'robot.adapter.customMessage is not a function'

### ISSUE THREAD

**Issue by bsord** [jonfairbanks/hubot-formatted-crypto#2]
Error in subject is received in the console when attempting to request price via slack.

**Comment by bsord** [comment]
The end user experience for this is that hubot does not respond to 'BOTNAME eth price' via slack.

**Comment by jonfairbanks** [comment]
Thanks for the report.

This should be resolved by the following PR: https://github.com/jonfairbanks/hubot-formatted-crypto/pull/1

This is now merged and available as 1.0.6 on NPM.
